version: "3.8"
services:
  quarkus:
    build:
      context: ./Quarkus
      args:
        buildno: 1
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"